### ISSUE TITLE
Route53 Config

### ISSUE THREAD

**Issue by rajat1saxena** [williamjacksn/docker-caddy-route53#61]
Hey, thanks for this project. I am new to AWS. I am getting the following error.

```
: operation error Route 53: ListHostedZonesByName, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, http response error StatusCode: 404, request to EC2 IMDS failed (order=https://acme.zerossl.com/v2/DV90/order/lMSQ3DpdQiLtWXyu_M71xw) (ca=https://acme.zerossl.com/v2/DV90)","attempt":5,"retrying_in":600,"elapsed":633.361800047,"max_duration":2592000}
```

I guess this is due to the fact I have not provided any token etc., to the dns config. Where in the AWS can I get these tokens from?

**Comment by williamjacksn** [comment]
Here is documentation from AWS about managing access keys: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html#Using_CreateAccessKey

Once you have an Access Key ID and Secret Access Key, refer to https://github.com/williamjacksn/docker-caddy-route53/blob/master/compose-example.yaml for an example of injecting them into the container.
